### ISSUE TITLE
List of certificate per folder

### ISSUE THREAD

**Issue by wloeven** [MicrosoftDocs/azure-docs.nl-nl#102]
It would be a good addition to provide a list of certificates that should be in the created folders:

acsBlob  = wildcard_blob_&lt;region&gt;_&lt;externalFQDN&gt;
ACSQueue = wildcard_queue_&lt;region&gt;_&lt;externalFQDN&gt;
ACSTable = wildcard_table_&lt;region&gt;_&lt;externalFQDN&gt;
Admin Extension Host = wildcard_adminhosting_&lt;region&gt;_&lt;externalFQDN&gt;
Admin Portal = adminportal_&lt;region&gt;_&lt;externalFQDN&gt;
ARM Admin = adminmanagement_&lt;region&gt;_&lt;externalFQDN&gt;
ARM Public = management_&lt;region&gt;_&lt;externalFQDN&gt;
KeyVault = wildcard_vault_&lt;region&gt;_&lt;externalFQDN&gt;
KeyVaultInternal = wildcard_adminvault_&lt;region&gt;_&lt;externalFQDN&gt;
Public Extension Host = wildcard_hosting_&lt;region&gt;_&lt;externalFQDN&gt;
Public Portal = portal_&lt;region&gt;_&lt;externalFQDN&gt;

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 971246f9-5230-23d8-24a3-34c12d5ed2de
* Version Independent ID: eba8d225-3a2d-3821-5fac-e434cbd271b2
* Content: [Azure Stack Public Key Infrastructure-certificaten voor de implementatie van de geïntegreerde Azure Stack-systemen valideren](https://docs.microsoft.com/nl-nl/azure/azure-stack/azure-stack-validate-pki-certs)
* Content Source: [articles/azure-stack/azure-stack-validate-pki-certs.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-stack/azure-stack-validate-pki-certs.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #18250](https://github.com/MicrosoftDocs/azure-docs/issues/18250) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @wloeven,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/18250.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
