### ISSUE TITLE
How to add my skillset to my indexer?

### ISSUE THREAD

**Issue by Axxeption** [MicrosoftDocs/azure-docs.nl-nl#116]
Hi! 
I created a extra skillset, but how can I tell my indexer to use that skillset instead of the one I created at the setup phase. I cannot find this in azure portal? Neither do I find how to add it using REST in the documentation?

Kind regards Axel.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c186c4b6-329f-7fe4-1833-460622f12ce3
* Version Independent ID: 27116ffd-185e-0f62-3576-618a9b73720e
* Content: [Een vaardigheden maken in een pijplijn cognitieve zoeken (Azure Search)](https://docs.microsoft.com/nl-nl/azure/search/cognitive-search-defining-skillset)
* Content Source: [articles/search/cognitive-search-defining-skillset.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/search/cognitive-search-defining-skillset.md)
* Service: **search**
* GitHub Login: @LuisCabrer
* Microsoft Alias: **luisca**

**Comment by Axxeption** [comment]
I think this is just not possible yet in Azure portal and you still need to use the JSON files like here (https://github.com/Azure/LearnAI-Cognitive-Search/blob/master/04-Lab-1-Text-Skills.md)

**Comment by CeciAc** [comment]
Hello, @Axxeption 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by LuisCabrer** [comment]
Hello @Axxeption ,
I am the program manager for Cognitive Search. You are right, the only way to modify the skillset for an indexer is to do it through the API. It is not yet possible in the portal.

Thanks!
-Luis
