### ISSUE TITLE
NSG rules

### ISSUE THREAD

**Issue by kwaazaar** [MicrosoftDocs/azure-docs.nl-nl#118]
I don't see specific rules to allow SSH to agent nodes, only AllowAzureLoadBalancerInbound and AllowVnetInbound.
Also, how can I restrict access to the Kubernetes API endpoint?

(I was watching the English version of the docs)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 9615c579-305d-2482-7eaf-2d120c75e8d5
* Version Independent ID: 064f4a10-bd74-f554-9550-781dd3e838cb
* Content: [Concepten - netwerken in Azure Kubernetes-Services (AKS)](https://docs.microsoft.com/nl-nl/azure/aks/concepts-network)
* Content Source: [articles/aks/concepts-network.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/aks/concepts-network.md)
* Service: **container-service**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by CeciAc** [comment]
Hello, @kwaazaar 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
