### ISSUE TITLE
Te gretig vertaald

### ISSUE THREAD

**Issue by Download** [MicrosoftDocs/azure-docs.nl-nl#120]
Er is hier iets te gretig vertaald. Als je het hebt over de 'impliciete goedkeuring stroom' weet niemand waar je het over hebt. Dit heet gewoon de 'implicit grant flow' en dat moet je niet gaan vertalen. Ik denk dat NL devs voorlopig beter de engelse versie van het artikel kunnen lezen.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 07eb21a8-9fd1-4cb6-3a08-c3fe6a6115ad
* Version Independent ID: 24f74ebb-3559-006d-dbde-b18a8b9e28fe
* Content: [Informatie over de OAuth2-impliciete stroom verlenen in Azure AD](https://docs.microsoft.com/nl-nl/azure/active-directory/develop/v1-oauth2-implicit-grant-flow)
* Content Source: [articles/active-directory/develop/v1-oauth2-implicit-grant-flow.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/active-directory/develop/v1-oauth2-implicit-grant-flow.md)
* Service: **active-directory**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by LisandroSu** [comment]
Hallo, @Download 
Hartelijk dank voor uw feedback. De opgevraagde pagina is automatisch vertaald. Dergelijke pagina's zijn niet altijd perfect leesbaar. We hebben onlangs aan de rechterkant een optie toegevoegd waarmee u de pagina in het Engels kunt lezen. U kunt dan omschakelen naar de Engelse versie zonder de taalinstellingen te wijzigen. 
Met vriendelijke groet, 
Het team van Microsoft DOCS International

**Comment by Download** [comment]
Met alle respect maar wat jullie hebben gedaan is echt dramatisch. Ik kwam er inderdaad later achter dat alles automatisch vertaald is. Jullie hebben ook geen unieke URLs voor de verschillende taal versies... Dus ik stuur iemand een link naar een pagina en hij krijgt niet de originele tekst maar een automatisch vertaalde (lees: bagger) versie van die tekst. Dit is echt dramatisch slecht en er is geen opt-out. Ik moet gewoon tegen iedereen zeggen: Wel even naar het Engels schakelen met dat vinkje en dan screenshots van het vinkje erbij gaan plakken etc). Wat een ramp!!

> U kunt dan omschakelen naar de Engelse versie

OMG. Sorry maar WAT??? Wie??? Wie heeft bedacht dat complexe documentatie voor technische onderwerpen zoals OAuth 2 automatisch door een translate service gooien een goed idee was?? Dit is echt verschrikkelijk!! 

Maar goed waarom meld ik het nog? Dit is hetzelfde MS dat al 2 keer (!!) zijn knowledge base heeft verhuisd waarbij steeds ALLE links naar knowledge base artikelen dood gingen. Een redirect pattern schrijven zodat oude URLs worden omgezet naar de nieuwe was te moeilijk... Waarom een knowledge base aanleggen als je de inhoud steeds dood laat gaan of nu geautomatiseerd door een vertaal service laat verkrachten???

Geef ons gewoon door Nederlandse experts vertaalde artikelen, of de originele Engelse, maar dit is echt helemaal niks.

**Comment by Download** [comment]
Ok it seems you can actually get a hard link to the English version of a document. E.g. the machine-molested/translated version of the page I was complaining about can be found at

https://docs.microsoft.com/nl-nl/azure/active-directory/develop/v1-oauth2-implicit-grant-flow

whereas the original English version can be found at:

https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-implicit-grant-flow

Unfortunately you will have to fight the MS website all the way as it assumes you prefer machine-molested/translated content over the original English version and will keep trying to redirect you to the nl-nl versions of every page you visit.

You guys really need to rethink your ideas about automatically translating. Really. This is not going to work. Ever.

**Comment by SonjaSaltzman** [comment]
Hello @Download - thank you for keeping your sense of humor (machine-molested). We are actively working on improving the machine translated content as it is helpful to some customers, but if you prefer to always see the English content, you can set your language preference via the language picker at the bottom left side of the site:
![image](https://user-images.githubusercontent.com/15201704/50870305-567dee00-136c-11e9-81af-cc4a8bfc29c1.png)
If you want to just quickly view English for a specific topic while staying in the Dutch chrome, you can use the toggle feature at the top right side: 
![image](https://user-images.githubusercontent.com/15201704/50870350-83ca9c00-136c-11e9-970d-ceca116d00fd.png)
We hope this will be helpful. We are also aware that there are edge cases (e.g. you set your preference to English, but your search engine returns a link containing the Dutch identifier), and are working on improving this behavior.

**Comment by Download** [comment]
> We are actively working on improving the machine translated content as it is helpful to some customers.

That is some big problem scope you are tackling in addition to azure docs. I believe it is still a mostly unsolved problem,

I challenge you to name *actual* Dutch customers that prefer the machine translated OAuth docs over the original English ones!  :p
