### ISSUE TITLE
Describe JWT processing

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-docs.nl-nl#121]
Suggestion: it would be insightful if you describe how the JWT processing works:
1. Client-side javascript calls the negotiate end-point on the local SignalR webapi 
2. This negotion endpoints detects if the user is authenticated through registered ASP.NET Core authentication middleware (please add a pointer to documentation on the internals); in this case the GitHub service
3. If authenticated, it includes a JWT generated by registered authentication middleware in the response
4. Client-side javascript uses the JWT to set up the connection with the Azure SignalR service
5. Client-side javascript invokes a server-side SignalR method
6. Azure SignalR service calls the webapi with the JWT attached that was used while setting up the connection
7. ASP.NET Core authentication middleware accepts the JWT and authenticates the user
8. Webapi method is run

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 32cea1c1-63e6-f332-419a-03ebdfb61bad
* Version Independent ID: 27404347-a7e3-08a3-5845-ed54f66b0483
* Content: [Zelfstudie voor het verifiëren van Azure SignalR Service-clients](https://docs.microsoft.com/nl-nl/azure/azure-signalr/signalr-authenticate-oauth)
* Content Source: [articles/azure-signalr/signalr-authenticate-oauth.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-signalr/signalr-authenticate-oauth.md)
* Service: **signalr**
* GitHub Login: @sffamily
* Microsoft Alias: **zhshang**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #21320](https://github.com/MicrosoftDocs/azure-docs/issues/21320) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @cveld 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
