### ISSUE TITLE
Kube-bench reports security issues

### ISSUE THREAD

**Issue by kwaazaar** [MicrosoftDocs/azure-docs.nl-nl#205]
kube-bench is a tool to check the nodes against a set of best practices (CIS). I tried this on my AKS-setup and it comes up with some issues. Can you indicate whethers these issues will be fixed or why not?

You can find kube-bench here: https://github.com/aquasecurity/kube-bench

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7010bd58-42b1-5c90-3253-05deed855be8
* Version Independent ID: c890efb2-cdaf-a3eb-d54f-0e7ccbd4314d
* Content: [Een cluster Azure Kubernetes Service (AKS) upgraden](https://docs.microsoft.com/nl-nl/azure/aks/upgrade-cluster)
* Content Source: [articles/aks/upgrade-cluster.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/aks/upgrade-cluster.md)
* Service: **container-service**
* GitHub Login: @gabrtv
* Microsoft Alias: **gamonroy**

**Comment by CeciAc** [comment]
Hello, @kwaazaar 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
