### ISSUE TITLE
Auto register Windows 10 device without AD connect

### ISSUE THREAD

**Issue by tijs0289** [MicrosoftDocs/azure-docs.nl-nl#210]
We need to automatically register/hybrid join/workplace join Windows 10 1809 based VDI desktops in Azure. These are managed using Azure AD DS. Therefore we need to know which GPO is appropriate. Auto-enrollment fails as of now because we require AD Connect as of the requirements, but we can not utilize that because we use Azure AD DS.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 28382bfc-6798-6aaf-6e65-3791a074b16b
* Version Independent ID: 2b0e4a55-349b-1378-4db1-9f551a202dfd
* Content: [Het plannen van hybride Azure Active Directory join-implementatie in Azure Active Directory (Azure AD)](https://docs.microsoft.com/nl-nl/azure/active-directory/devices/hybrid-azuread-join-plan#feedback)
* Content Source: [articles/active-directory/devices/hybrid-azuread-join-plan.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/active-directory/devices/hybrid-azuread-join-plan.md)
* Service: **active-directory**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by CeciAc** [comment]
Hello, @tijs0289 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
