### ISSUE TITLE
Python Azure Function Apps cannot be imported

### ISSUE THREAD

**Issue by DanielYnformed** [MicrosoftDocs/azure-docs.nl-nl#212]
Hello, I am not able to import Python Function Apps into an APIM, although I have set the authentication on "Anonymous" or "Function". Is this still a work-in-progress? Besides, I would like to know if there is a way to develop an API in python (no matter what type of app) and import this python project as new API in an Azure APIM. Is still even possible? I cannot find any documentation on this matter.

Thanks in advance!

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a0b38af1-81e7-341a-d7bf-e471ea7585e5
* Version Independent ID: 6d16fd43-249e-5afc-062a-2e019eade30e
* Content: [Een Azure-functie-app als API importeren in Azure API Management](https://docs.microsoft.com/nl-nl/azure/api-management/import-function-app-as-api)
* Content Source: [articles/api-management/import-function-app-as-api.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/api-management/import-function-app-as-api.md)
* Service: **api-management**
* GitHub Login: @mikebudzynski
* Microsoft Alias: **apimpm**

**Comment by CeciAc** [comment]
Hello, @DanielYnformed 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
