### ISSUE TITLE
Networking connection policy

### ISSUE THREAD

**Issue by djimmo** [MicrosoftDocs/azure-docs.nl-nl#215]
The keyword "new" should be removed when created the authKey string in the example in the Networking connection policy:

var serviceEndpoint = new Uri("https://contoso.documents.net");
var authKey = "your authKey from the Azure portal";
DocumentClient client = new DocumentClient(serviceEndpoint, authKey,
new ConnectionPolicy
{
   ConnectionMode = ConnectionMode.Direct,
   ConnectionProtocol = Protocol.Tcp
});

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 19819758-be79-2347-d1d9-7c950d8513ae
* Version Independent ID: 8099f2c8-f8bc-6459-c6fe-6b65b02fc6a2
* Content: [Azure Cosmos DB tips voor betere prestaties voor .NET](https://docs.microsoft.com/nl-nl/azure/cosmos-db/performance-tips)
* Content Source: [articles/cosmos-db/performance-tips.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/cosmos-db/performance-tips.md)
* Service: **cosmos-db**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #23319](https://github.com/MicrosoftDocs/azure-docs/issues/23319) via [**ZenHub**](https://www.zenhub.com/)
