### ISSUE TITLE
Contradiction regarding retention period

### ISSUE THREAD

**Issue by markbeij** [MicrosoftDocs/azure-docs.nl-nl#223]
Azure Cosmos DB takes snapshots of your data every four hours. At any given time, only the last two snapshots are retained.

Contradicts

If you have accidentally deleted or corrupted your data, you should contact Azure support within eight hours so that the Azure Cosmos DB team can help you restore the data from the backups.

Two snapshots retained with an interval of four hours means that worst case scenario the latest snapshot is four hours and one minute ago. Which statement is correct?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 887a7740-51a1-80b6-5d0f-704621ad50c7
* Version Independent ID: 642c593f-9563-cd62-e23f-a47bb6e3e421
* Content: [Automatische, online back-up en gegevens op aanvraag voor herstellen in Azure Cosmos DB](https://docs.microsoft.com/nl-nl/azure/cosmos-db/online-backup-and-restore#backup-retention-period)
* Content Source: [articles/cosmos-db/online-backup-and-restore.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/cosmos-db/online-backup-and-restore.md)
* Service: **cosmos-db**
* GitHub Login: @kanshiG
* Microsoft Alias: **govindk**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24292](https://github.com/MicrosoftDocs/azure-docs/issues/24292) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @markbeij 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/24292.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
