### ISSUE TITLE
Label voor Engels staat Nederlands

### ISSUE THREAD

**Issue by sjoerdkersten** [MicrosoftDocs/azure-docs.nl-nl#224]
Label voor Engels staat Nederlands : https://docs.microsoft.com/nl-be/azure/cognitive-services/text-analytics/language-support

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 62643b2a-6080-150d-7e04-11b0250f22dc
* Version Independent ID: e7ffbecc-52e6-f356-e3d6-d3392711921c
* Content: [Taalondersteuning - Tekstanalyse-API - Azure Cognitive Services](https://docs.microsoft.com/nl-be/azure/cognitive-services/text-analytics/language-support)
* Content Source: [articles/cognitive-services/text-analytics/language-support.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/cognitive-services/text-analytics/language-support.md)
* Service: **cognitive-services**
* GitHub Login: @ashmaka
* Microsoft Alias: **ashmaka**

**Comment by LisandroSu** [comment]
@sjoerdkersten , hartelijk dank voor uw feedback en suggestie! 
		 
Uw suggestie wordt meegenomen tijdens de productie. Dit artikel wordt in de volgende lokalisatieronde opnieuw gepubliceerd. 
		 
Het Microsoft C&E-lokalisatieteam

**Comment by CeciAc** [comment]
Hallo,   @sjoerdkersten 

Hartelijk   dank voor uw feedback.
Ons   taalteam heeft uw taalkundige suggesties beoordeeld en geaccepteerd. We   hebben uw feedback geïmplementeerd en op de Docs-site gepubliceerd in de   bijgewerkte artikelen op de volgende pagina’s https://docs.microsoft.com/nl-be/azure/cognitive-services/text-analytics/language-support 

We  stellen uw bijdrage aan onze artikelen zeer op prijs en we hopen dat u ons uw   waardevolle feedback zal blijven geven.
Met   vriendelijke groet,
Het team van Microsoft DOCS International
