### ISSUE TITLE
QnA Maker Train API behavior is undocumented

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/azure-docs.nl-nl#225]
QnA Maker apparently has a Train API, but it is not documented at https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75ff.

It is not documented what the expected response should be.

The link to the Train API on https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base is a sample, not documentation.

Furthermore, in the Google search cache I found that **the Train process is run only after 50 feedback entries are received** but this is listed nowhere on https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: e302f635-c2b9-e505-7b9e-d947dab75514
* Version Independent ID: 2c1e8216-c9d5-68bd-cbca-6c80dcb2f2b3
* Content: [Verbetering van knowledge base - QnA Maker - Azure Cognitive Services](https://docs.microsoft.com/nl-nl/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base)
* Content Source: [articles/cognitive-services/QnAMaker/How-To/improve-knowledge-base.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/cognitive-services/QnAMaker/How-To/improve-knowledge-base.md)
* Service: **cognitive-services**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by hansmbakker** [comment]
Screenshot from Google:
![image](https://user-images.githubusercontent.com/3463496/52571614-2bc50080-2e16-11e9-886d-ffe7b23f13d2.png)

I see that this links to an old page (which redirects to qnamaker.ai now) but it seems that feedback items still are not picked up immediately.

**Comment by hansmbakker** [comment]
Also it is not clear if calls to the Train will result in a suggestion being created in the QnA Maker portal that still needs to be accepted by a moderator, or that the model will automatically be retrained and published.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24709](https://github.com/MicrosoftDocs/azure-docs/issues/24709) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hansmbakker 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/24709.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
