### ISSUE TITLE
Zeer slechte vertaling naar Nederlands

### ISSUE THREAD

**Issue by jorikcaljouw** [MicrosoftDocs/azure-docs.nl-nl#226]
Ik hoop van harte dat dit een automatisch gegenereerde vertaling is, maar als dit door de Microsoft Translator gedaan is, is het geen goed visitekaartje!
De eerste 5 zinnen zijn allemaal grammaticaal incompleet of incorrect. Ik heb verder maar niet gelezen...

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 8b52a210-1be6-4e5f-d95c-8ea7b87919ca
* Version Independent ID: 02a43ebb-7471-d7ff-4f7e-84c9f7a66326
* Content: [Back-up en herstellen met de Microsoft Authenticator-app - Azure Active Directory](https://docs.microsoft.com/nl-nl/azure/active-directory/user-help/user-help-auth-app-backup-recovery)
* Content Source: [articles/active-directory/user-help/user-help-auth-app-backup-recovery.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/active-directory/user-help/user-help-auth-app-backup-recovery.md)
* Service: **active-directory**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by CeciAc** [comment]
Hallo, @jorikcaljouw 
Hartelijk dank voor uw feedback. De opgevraagde pagina is automatisch vertaald. Dergelijke pagina's zijn niet altijd perfect leesbaar. We hebben onlangs aan de rechterkant een optie toegevoegd waarmee u de pagina in het Engels kunt lezen. U kunt dan omschakelen naar de Engelse versie zonder de taalinstellingen te wijzigen. 
Met vriendelijke groet, 
Het team van Microsoft DOCS International
