### ISSUE TITLE
Confusion about what happens when the cache is expired, combined with eTag (Verizon Standard)

### ISSUE THREAD

**Issue by frankfru** [MicrosoftDocs/azure-docs.nl-nl#228]
We want to use a short expiration time (say Cache Control: max-age=30), combined with ETag for validation.
We use Azure CDN Verizon Standard with a storage account as the origin.
The idea is that after expiration of the cache (after 30s), the CDN validates the data in the cache using the ETag, and only when the Etag differs from the origin, the data is fetched from the origin.
Using the Chrome devtools I can verifiy that, from the browser's perspective, it's works this way.
However. I'm confused by this sentence in the documentation: 'CDN cache duration: Specifies the amount of time for which a resource is cached on the Azure CDN.'
What happens after expiration? Is the entry deleted from the CDN cache and consequently  on the next request the data is retrieved again from the origin(in which case the CDN could still return 304 if the ETag from the origin matches the ETag from the request of the client), or is the cache just marked as stale and the CDN validates the cache with the origin using the ETag?
And if the latter is the cache (which I expect), when is a cache entry deleted from cache? Never?
i

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: e822ee79-227c-54d3-fb83-9e30bb361811
* Version Independent ID: e6e883c6-30fd-c660-64b1-f849f04ddfa7
* Content: [Hoe caching werkt](https://docs.microsoft.com/nl-nl/azure/cdn/cdn-how-caching-works)
* Content Source: [articles/cdn/cdn-how-caching-works.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/cdn/cdn-how-caching-works.md)
* Service: **cdn**
* GitHub Login: @mdgattuso
* Microsoft Alias: **magattus**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25687](https://github.com/MicrosoftDocs/azure-docs/issues/25687) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @frankfru 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/25687

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
