### ISSUE TITLE
Use key vault references  locally

### ISSUE THREAD

**Issue by tomkluskens** [MicrosoftDocs/azure-docs.nl-nl#229]
"Key Vault references currently only support system-assigned managed identities. User-assigned identities cannot be used."

When will be the use of key vault references supported when debugging  a function app locally?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7feaa3d0-7233-a3cb-cb9b-a9a55b1f0d7a
* Version Independent ID: f41f9d51-52f8-1f45-1043-1344a3b74458
* Content: [Verwijzingen naar Key Vault - Azure App Service](https://docs.microsoft.com/nl-nl/azure/app-service/app-service-key-vault-references)
* Content Source: [articles/app-service/app-service-key-vault-references.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/app-service/app-service-key-vault-references.md)
* Service: **app-service**
* GitHub Login: @mattchenderson
* Microsoft Alias: **mahender**

**Comment by FrankHoogmans** [comment]
I found a related issue (without response): https://github.com/Azure/azure-functions-host/issues/3907

I would really like to be able to locally debug with the same Key Vault References as in the other environments.

**Comment by CeciAc** [comment]
Hello, @tomkluskens 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
