### ISSUE TITLE
Size when partitioning is vague

### ISSUE THREAD

**Issue by tomkuijsten** [MicrosoftDocs/azure-docs.nl-nl#231]
This statement:

"Service Bus creates 16 copies (16 partitions) of the entity for each GB you specify."

Conflicts with the next line:

"As such, if you create a queue that's 5 GB in size, with 16 partitions the maximum queue size becomes (5 * 16) = 80 GB."

I might read it wrong, but if there are 16 partitions PER GB (quote 1), then 5 GB would end up in 16x5=80 partitions? But that's not what your saying, the second quote still mentioned 16 partitioned. So my question: Will there always be 16 partitions, no matter what size used?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 14b28704-f660-c413-a0fe-cb1d469fe35c
* Version Independent ID: 403df162-e673-527f-8e72-8abf43d8b5cc
* Content: [Gepartitioneerde Azure Service Bus-wachtrijen en onderwerpen maken](https://docs.microsoft.com/nl-nl/azure/service-bus-messaging/service-bus-partitioning#feedback)
* Content Source: [articles/service-bus-messaging/service-bus-partitioning.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/service-bus-messaging/service-bus-partitioning.md)
* Service: **service-bus-messaging**
* GitHub Login: @axisc
* Microsoft Alias: **aschhab**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #26713](https://github.com/MicrosoftDocs/azure-docs/issues/26713) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @tomkuijsten 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/26713

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
