### ISSUE TITLE
Layout table Bindings is broken

### ISSUE THREAD

**Issue by djeffa** [MicrosoftDocs/azure-docs.nl-nl#233]
The layout of the table in the Bindings paragraph is broken and only shows a texted based table that isn't aligned

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1df5e2bd-489d-19b2-87d3-d993ebb82021
* Version Independent ID: 9e9d9ded-8f40-22be-4654-48c87f2c59e8
* Content: [Overzicht van Azure Functions runtime-versies](https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-versions#feedback)
* Content Source: [articles/azure-functions/functions-versions.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-functions/functions-versions.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by CeciAc** [comment]
Hello, @djeffa 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #28486](https://github.com/MicrosoftDocs/azure-docs/issues/28486) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hi @ishasahni1 
Assigning the issue back to you since it looks like is due the source was recently updated
best

**Comment by ishasahni1** [comment]
@CeciAc we are going to work on getting this file localized and address the format issue.

**Comment by ishasahni1** [comment]
@djeffa this issue has been addressed now, the table is rendering correctly https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-reference.

Thank you for your valuable feedback again.

@CeciAc
