### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by bvduijn** [MicrosoftDocs/azure-docs.nl-nl#234]
Hi,
After enabling this in our masterpage we do get telemetry in AppInsights. However everytime a user opens a page the tracing also shows a script error with the following message:

url: https://az416426.vo.msecnd.net/scripts/a/ai.0.js
message: The browser's same-origin policy prevents us from getting the details of this exception. Consider using 'crossorigin' attribute.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a1d5591a-bdb0-7eed-9697-4f2c7f3cc807
* Version Independent ID: 301d5ed0-863e-7a46-0d93-023f27e29f89
* Content: [Een SharePoint-site met Application Insights bewaken](https://docs.microsoft.com/nl-nl/azure/azure-monitor/app/sharepoint#feedback)
* Content Source: [articles/azure-monitor/app/sharepoint.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-monitor/app/sharepoint.md)
* Service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by CeciAc** [comment]
Hello, @bvduijn 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
