### ISSUE TITLE
Link to version history leads to Technet page that links to another Microsoft Docs Page

### ISSUE THREAD

**Issue by MarkDNL** [MicrosoftDocs/azure-docs.nl-nl#309]
The link in the Version History section leads to and old Technet page: https://social.technet.microsoft.com/wiki/contents/articles/51049.asr-deployment-planner-version-history.aspx

The Technetpage just contains a link to https://docs.microsoft.com/en-us/azure/site-recovery/site-recovery-deployment-planner-history. A direct link would be better, instead of the Technet page.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: aa9a9a9e-e47f-2c35-752e-4d026f0fca93
* Version Independent ID: c23d2cb9-c2d0-505c-5a58-53074fcd373b
* Content: [Over de Azure Site Recovery Deployment Planner voor herstel na noodgevallen van virtuele VMware-machines naar Azure](https://docs.microsoft.com/nl-nl/azure/site-recovery/site-recovery-deployment-planner)
* Content Source: [articles/site-recovery/site-recovery-deployment-planner.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/site-recovery/site-recovery-deployment-planner.md)
* Service: **site-recovery**
* GitHub Login: @mayurigupta13
* Microsoft Alias: **mayg**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #31287](https://github.com/MicrosoftDocs/azure-docs/issues/31287) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @MarkDNL

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/31287

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
