### ISSUE TITLE
Extraction zip files has limitations?

### ISSUE THREAD

**Issue by madiepev** [MicrosoftDocs/azure-docs.nl-nl#340]
My indexer shows an error for two zip files (size of 800MB) saying that the zip file has "the size of ... bytes, which exceeds the maximum size for document extraction for your curent service tier." Azure Search is already set on a Standard tier. Is the solution to go to a higher tier? Cause from the documentation I gather that the limit is the same across all Standard tiers? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 63559d85-a673-b5cb-6ac0-465c988774c3
* Version Independent ID: 3cfbd312-0eb4-d2a4-0819-566a197d6475
* Content: [Azure Blob storage-inhoud voor zoeken in volledige tekst - Azure Search-index](https://docs.microsoft.com/nl-nl/azure/search/search-howto-indexing-azure-blob-storage#feedback)
* Content Source: [articles/search/search-howto-indexing-azure-blob-storage.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/search/search-howto-indexing-azure-blob-storage.md)
* Service: **search**
* GitHub Login: @mgottein
* Microsoft Alias: **magottei**

**Comment by CeciAc** [comment]
Hello, @madiepev

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
