### ISSUE TITLE
Is application property 'type' a reserved keyword?

### ISSUE THREAD

**Issue by sandervandevelde** [MicrosoftDocs/azure-docs.nl-nl#349]
In our project we use an application property named 'type':
"applicationProperties": {
    ...
    "type": "heartbeat",
}
this 'type' property does not work as expected. 
Is it a reserved keyword? If so, how can I get around this?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 8be1f717-4e46-0a00-b4e3-823245834d3e
* Version Independent ID: 5c3f75ba-5eb2-0827-30ff-13c6cf95fc3f
* Content: [Query op de Azure IoT Hub-berichtroutering](https://docs.microsoft.com/nl-nl/azure/iot-hub/iot-hub-devguide-routing-query-syntax)
* Content Source: [articles/iot-hub/iot-hub-devguide-routing-query-syntax.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/iot-hub/iot-hub-devguide-routing-query-syntax.md)
* Service: **iot-hub**
* GitHub Login: @ash2017
* Microsoft Alias: **asrastog**

**Comment by CeciAc** [comment]
Hello, @sandervandevelde 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by sandervandevelde** [comment]
Sorry, I now see I posted my question on the 'translated' page.
