### ISSUE TITLE
ensble snapsot debugging for Azure functions

### ISSUE THREAD

**Issue by galletto58** [MicrosoftDocs/azure-docs.nl-nl#408]
This page does not mention Azure Functions, and I've been searching for a while now. 
Hoe do I enable snapshot debugging for azure functions? I'm missing the UI shown here for App services

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 279763aa-b638-e2bc-cdb8-52c7bfe426ee
* Version Independent ID: df3a411a-b8da-fccb-9c0b-aeb60a7c8baa
* Content: [Snapshot Debugger voor .NET-apps in Azure App Service inschakelen](https://docs.microsoft.com/nl-nl/azure/azure-monitor/app/snapshot-debugger-appservice?toc=%2Fazure%2Fazure-monitor%2Ftoc.json#feedback)
* Content Source: [articles/azure-monitor/app/snapshot-debugger-appservice.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/azure-monitor/app/snapshot-debugger-appservice.md)
* Service: **application-insights**
* GitHub Login: @brahmnes
* Microsoft Alias: **brahmnes**

**Comment by CeciAc** [comment]
Hello, @galletto58

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
