### ISSUE TITLE
Force MFA when opening the desktop client

### ISSUE THREAD

**Issue by Jorrit05** [MicrosoftDocs/azure-docs.nl-nl#418]
Hi, 
I love the user experience when opening my laptop just jumping into my VDI's. 

I was wondering though if it is going to be possible to enforce MFA authentication on the dekstop client. At the moment it lets me go directly into my resources. 

Thanks in advance and kind regards,
Jorrit

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 524e47b0-1295-7d07-0cbc-86e6daaa1358
* Version Independent ID: 1cb3a5d8-4f16-583c-ad85-325f7638a873
* Content: [Verbinding maken met Windows virtuele bureaublad Preview-versie van Windows 10 of Windows 7 - Azure](https://docs.microsoft.com/nl-nl/azure/virtual-desktop/connect-windows-7-and-10#feedback)
* Content Source: [articles/virtual-desktop/connect-windows-7-and-10.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/virtual-desktop/connect-windows-7-and-10.md)
* Service: **virtual-desktop**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by CeciAc** [comment]
Hello, @Jorrit05 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
