### ISSUE TITLE
Issue regarding subscribing to feed

### ISSUE THREAD

**Issue by StephanElst** [MicrosoftDocs/azure-docs.nl-nl#465]
When clicking the button  subscribe to subscribe to a feed the application reports an error. This error reads: Something went wrong. 
This issue pops up several times online, but without an adequate answer. 
found that the application checks the certificate store. If the user deletes the non-relevant certificates from the personal store and restarts the application and subscribes to the feed it works again.  

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1e0fc055-dfac-dfed-28ca-3d0904f7137a
* Version Independent ID: 525f9b35-c2ae-44cf-9074-c69fdf7f26cd
* Content: [Verbindingen van extern bureaublad-client in Windows virtueel bureaublad - Azure](https://docs.microsoft.com/nl-nl/azure/virtual-desktop/troubleshoot-client-connection#feedback)
* Content Source: [articles/virtual-desktop/troubleshoot-client-connection.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/virtual-desktop/troubleshoot-client-connection.md)
* Service: **virtual-desktop**
* GitHub Login: @ChJenk
* Microsoft Alias: **v-chjenk**

**Comment by srvbpigh** [comment]
Hello, @StephanElst
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35670](https://github.com/MicrosoftDocs/azure-docs/issues/35670) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @StephanElst

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35670

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
