### ISSUE TITLE
AcquireToken Mothed Issue

### ISSUE THREAD

**Issue by marcvdberg** [MicrosoftDocs/azure-docs.nl-nl#472]
I wanted to use the office365_unsubscribe.ps1 script to stop data coming in to a ResourceGroup, but had an error with the AcquireToken method on line 49.

Error message: Method invocation failed because [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method
 named 'AcquireToken'.

Does anyone know how to solve this issue?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 06524f5f-beb1-de55-b30b-8dcc0513191a
* Version Independent ID: 730c62fb-ea4d-ed73-af86-ca8d5a959ff7
* Content: [Office 365-oplossing in Azure](https://docs.microsoft.com/nl-nl/azure/azure-monitor/insights/solution-office-365#feedback)
* Content Source: [articles/azure-monitor/insights/solution-office-365.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/azure-monitor/insights/solution-office-365.md)
* Service: **azure-monitor**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by srvbpigh** [comment]
Hello, @marcvdberg
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @marcvdberg 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
