### ISSUE TITLE
How to use image after deploying to IoT Edge?

### ISSUE THREAD

**Issue by lkoppenol** [MicrosoftDocs/azure-docs.nl-nl#480]
I deployed an image from the ACR repository behind AMLS to IoT Edge. It is listed as module there. How do I use it? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 38e267fb-efa2-dab5-aa83-4a4addc39ee8
* Version Independent ID: e1d506d0-c6bf-47ed-a12c-7bb50416c865
* Content: [Hoe en waar modellen moeten worden geïmplementeerd - Azure Machine Learning service](https://docs.microsoft.com/nl-nl/azure/machine-learning/service/how-to-deploy-and-where)
* Content Source: [articles/machine-learning/service/how-to-deploy-and-where.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/machine-learning/service/how-to-deploy-and-where.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @jpe316
* Microsoft Alias: **jordane**

**Comment by srvbpigh** [comment]
Hello, @lkoppenol
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lkoppenol

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
