### ISSUE TITLE
Can't create an AKS Cluster.

### ISSUE THREAD

**Issue by geertberkers** [MicrosoftDocs/azure-docs.nl-nl#483]
I was following this tutorial, everything works untill the command "az aks create". Im getting an Operation Failed with status Bad Request. Details: Internal server error. The az cli installed is version 2.0.70 (and aks-preview 0.4.6)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: bc86c3af-f6c7-4c48-e157-54abbc5958ff
* Version Independent ID: 3611b478-6df6-f5cd-563d-2fff6cfec9ef
* Content: [Azure Active Directory integreren met de Azure Kubernetes-service](https://docs.microsoft.com/nl-nl/azure/aks/azure-ad-integration-cli#feedback)
* Content Source: [articles/aks/azure-ad-integration-cli.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/aks/azure-ad-integration-cli.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @geertberkers
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by geertberkers** [comment]
I noticed that no matter what I tried, creating a cluster using the Azure CLI didn't work. There was just a problem with creating the cluster. Even  `az aks create -g $resourcegroup -n $aksname --node-count 1` gave  the same result, so its not bound to the Azure Active Directory I guess.

**Comment by CeciAc** [comment]
Hello, @geertberkers

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
