### ISSUE TITLE
Verification of publisher domain failed.

### ISSUE THREAD

**Issue by twiettwiet** [MicrosoftDocs/azure-docs.nl-nl#506]
The hosted file is visible at: https://cupweb6.nl/.well-known/microsoft-identity-association.json,

But i keep getting the error:
Verification of publisher domain failed. The application was not found. If the application was just created, wait a few minutes and refresh the page. [7jLp5]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 61edea45-b5d6-05b3-33c3-2265ef8cb309
* Version Independent ID: c7d5813c-5cf1-44c3-88ff-3c194d3e44ad
* Content: [Het domein van de uitgever van een toepassing configureren](https://docs.microsoft.com/nl-nl/azure/active-directory/develop/howto-configure-publisher-domain#feedback)
* Content Source: [articles/active-directory/develop/howto-configure-publisher-domain.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/develop/howto-configure-publisher-domain.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @twiettwiet
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @twiettwiet

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by twiettwiet** [comment]
The reason that I couldn't "Verify my publisher domain" is that my registration was not created in my [owned applications] or [default folder] but in my [personal account]

It would have been useful if this was mentioned in the documentation.
