### ISSUE TITLE
docker environment variables into Function module?

### ISSUE THREAD

**Issue by RudyEvers** [MicrosoftDocs/azure-docs.nl-nl#515]
How do I get a docker environment variable into the CSharpFunction.cs ? For Example een connection string that is used in a function.

I am working on a Azure IoT Edge project and I cannot figure out how to get custom docker environment variables in my C# class.

So I have Azure Functions running as a module on a IoT Edge environment. On this Edge environment also Azure Blob Storage is running as a module. The Azure Function has to get some information from a blob container. At the moment Blob connection string is hard coded, but with the possibility of having more Edge environment I want to be able to set this connection string through the docker environment variable.

So when I create a new Edge device in Azure and add a Function Module the connection string of the Blob storage must be set via a Environment Variable.
Can't find any documentation how to achieve this. Is it possible?

![azure function module](https://user-images.githubusercontent.com/38738862/65155877-56bba680-da2e-11e9-9da3-794495d86ff3.PNG)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a7852968-3c54-5584-df91-b01521efae43
* Version Independent ID: c7340985-f6d2-2bf8-71e5-ee62dadb25e3
* Content: [Zelfstudie: een Azure-functie implementeren op een apparaat - Azure IoT Edge](https://docs.microsoft.com/nl-nl/azure/iot-edge/tutorial-deploy-function?toc=%2fazure%2fazure-functions%2ftoc.json)
* Content Source: [articles/iot-edge/tutorial-deploy-function.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/iot-edge/tutorial-deploy-function.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by srvbpigh** [comment]
Hello, @RudyEvers
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @RudyEvers

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
