### ISSUE TITLE
The destination directory is deleted when a file is moved and the file is renamed with the destination directory name

### ISSUE THREAD

**Issue by avanhelden** [MicrosoftDocs/azure-docs.nl-nl#518]
It seems that moving a file is not working. It moves the file, renames it with the destination directory folder name and deletes the destination folder. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 4810e7d6-28ed-d956-44b6-77fe62b579e5
* Version Independent ID: 98b5df43-40de-ee10-e63c-c5f15eca1a16
* Content: [Bron transformatie in toewijzings gegevens stroom-Azure Data Factory](https://docs.microsoft.com/nl-nl/azure/data-factory/data-flow-source#feedback)
* Content Source: [articles/data-factory/data-flow-source.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/data-factory/data-flow-source.md)
* Service: **data-factory**
* GitHub Login: @kromerm
* Microsoft Alias: **makromer**

**Comment by srvbpigh** [comment]
Hello, @avanhelden
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @avanhelden

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
