### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by SonerMulder** [MicrosoftDocs/azure-docs.nl-nl#530]
micro soft -&gt; Microsoft
para meter -&gt; parameter
voor beeld -&gt; voorbeeld

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 73d91616-a93f-84af-7900-5aa34b361ffd
* Version Independent ID: f202a678-4853-d024-55c5-19f89558415c
* Content: [De SendGrid-e-mail service (.NET) gebruiken](https://docs.microsoft.com/nl-nl/azure/sendgrid-dotnet-how-to-send-email#feedback)
* Content Source: [articles/sendgrid-dotnet-how-to-send-email.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/sendgrid-dotnet-how-to-send-email.md)
* Service: **multiple**
* GitHub Login: @thinkingserious
* Microsoft Alias: **erikre**

**Comment by srvbpigh** [comment]
Hello, @SonerMulder
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SonerMulder
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/nl-nl/azure/sendgrid-dotnet-how-to-send-email#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
