### ISSUE TITLE
Leaked Credentials Detection

### ISSUE THREAD

**Issue by GitTune** [MicrosoftDocs/azure-docs.nl-nl#531]
I assume Leaked Credentials detection is only working with cloud accounts and if the ADConnect is configured to user password hash sync. Is that correct? For example, on a federated domain, using ADFS, this would not work unless the password hashes are synced too? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 198f0e69-af2a-8c82-041a-c5ca4126f02f
* Version Independent ID: 4be57788-f1c2-d6d4-b94a-a59350a618a7
* Content: [Detectie van Azure Active Directorye Risico's](https://docs.microsoft.com/nl-nl/azure/active-directory/reports-monitoring/concept-risk-events)
* Content Source: [articles/active-directory/reports-monitoring/concept-risk-events.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/reports-monitoring/concept-risk-events.md)
* Service: **active-directory**
* Sub-service: **report-monitor**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by srvbpigh** [comment]
Hello, @GitTune
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @GitTune

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
