### ISSUE TITLE
Unclear sentence

### ISSUE THREAD

**Issue by Mortana89** [MicrosoftDocs/azure-docs.nl-nl#541]
The following sentence is pretty unclear;
Throughput provisioned on a database can be shared by the containers within that database. A maximum of 25 containers can share the throughput provisioned on the database. Beyond 25 containers, for every new container created within that database can share a portion of database throughput with other collections already available in the database. The amount of throughput that can be shared is dependent on the number of the containers provisioned in the database.

Previously, when setting throughput on DB level, we need 100RU per container at a minimum.
So, when we have 10 containers in the database, we need at least 1000RU on the database. Does this still count?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0f2b93a5-28b8-db4a-ab64-6342d3aafc63
* Version Independent ID: 245586f2-63e1-1e78-a5dd-21e8fa2cc5d3
* Content: [Doorvoer inrichten op Azure Cosmos-containers en databases](https://docs.microsoft.com/nl-nl/azure/cosmos-db/set-throughput#feedback)
* Content Source: [articles/cosmos-db/set-throughput.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/cosmos-db/set-throughput.md)
* Service: **cosmos-db**
* GitHub Login: @rimman
* Microsoft Alias: **rimman**

**Comment by srvbpigh** [comment]
Hello, @Mortana89
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Mortana89

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/40268

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
