### ISSUE TITLE
Matig geschreven

### ISSUE THREAD

**Issue by SonerMulder** [MicrosoftDocs/azure-docs.nl-nl#542]
Zit vol met typfouten en slechte vertalingen.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: afed582b-fb3f-30b3-b119-6c4a9218bf34
* Version Independent ID: d4cf3473-21c1-2409-e7ac-9ad93fbc5895
* Content: [Azure Storage wacht rijen en Service Bus wacht rijen vergeleken en met contrast](https://docs.microsoft.com/nl-nl/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted)
* Content Source: [articles/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted.md)
* Service: **service-bus-messaging**
* GitHub Login: @axisc
* Microsoft Alias: **aschhab**

**Comment by srvbpigh** [comment]
Hello, @SonerMulder
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @SonerMulder 
Hartelijk dank voor uw feedback. De opgevraagde pagina is automatisch vertaald. Dergelijke pagina's zijn niet altijd perfect leesbaar. We hebben onlangs aan de rechterkant een optie toegevoegd waarmee u de pagina in het Engels kunt lezen. U kunt dan omschakelen naar de Engelse versie zonder de taalinstellingen te wijzigen. 
Met vriendelijke groet, 
Het team van Microsoft DOCS International
