### ISSUE TITLE
Conditional Access policies evaluation pattern

### ISSUE THREAD

**Issue by GitTune** [MicrosoftDocs/azure-docs.nl-nl#544]
Conditional Access policies are evaluated when:
A user initially signs in to a web app, mobile or desktop application.
A mobile or desktop application that uses modern authentication, uses a refresh token to acquire a new access token. By default this check is once an hour.

Is this also applicable to Azure Identity Protection Sign-in policy? If I require MFA for medium risk, does this MFA prompt the user when I configured the Azure Identity Protection Sign-in policy. Or is a Conditional Acces rule needed on top of this? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 3389d38b-4471-0d2d-ceab-580c2188febe
* Version Independent ID: 6f2ad044-0f8e-f4ad-149b-ba8b54aeda50
* Content: [Wat is de locatievoorwaarde in Azure Active Directory voor voorwaardelijke toegang?](https://docs.microsoft.com/nl-nl/azure/active-directory/conditional-access/location-condition#named-locations)
* Content Source: [articles/active-directory/conditional-access/location-condition.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/conditional-access/location-condition.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @GitTune
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @GitTune 

Your contribution is much appreciated. Your feedback is related to the original documentation.
https://github.com/MicrosoftDocs/azure-docs/issues/41914

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
