### ISSUE TITLE
"Synchronization is currently in progress" comes up in confusing situation

### ISSUE THREAD

**Issue by valentijnscholten** [MicrosoftDocs/azure-docs.nl-nl#548]
Hi,

The "Synchronization is currently in progress" is also shown when somebody else has left the Azure AD Connect wizard open (when used on a server, multiple users can be logged in - even in disconnected state).

Today I spent quite some time trying to the kill the alleged "in progress sync" only to find out there was some wizard open in somebody else disconnected session :)

Ideally the (error) message should be changed, but in the mean time it might be good to mention this scenario on this page as the wizard will lead you here when you click "Learn more" in the error message.

Valentijn

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c2026376-29c3-49fe-c0e4-a766e46aab68
* Version Independent ID: 0803163d-8b43-4d27-c0ef-14db64ff2061
* Content: [Azure AD Connect-synchronisatie: Scheduler](https://docs.microsoft.com/nl-nl/azure/active-directory/hybrid/how-to-connect-sync-feature-scheduler)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sync-feature-scheduler.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/hybrid/how-to-connect-sync-feature-scheduler.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @valentijnscholten
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @valentijnscholten

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43322

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
