### ISSUE TITLE
Code: 404, Message: Resource not found activityId: 

### ISSUE THREAD

**Issue by wilcoblom** [MicrosoftDocs/azure-docs.nl-nl#550]
We have a durable Azure Function, which sends back http 202 accepted, location and retry-after headers, which works correctly when we execute this using an Azure Function Logic App Action. When we try to create a new custom Logic App action for this Durable Azure Function (using the polling pattern: https://docs.microsoft.com/nl-nl/azure/logic-apps/logic-apps-create-api-app#perform-long-running-tasks-with-the-polling-action-pattern), we get the following error whatever we do: Code: 404, Message: Resource not found activityId: "". Can you help us with this?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: aed00dab-131e-ecde-1416-66b3590a9e65
* Version Independent ID: c6071445-f111-370a-d266-68972b105427
* Content: [Web-Api's maken & REST-Api's voor Azure Logic Apps](https://docs.microsoft.com/nl-nl/azure/logic-apps/logic-apps-create-api-app#perform-long-running-tasks-with-the-polling-action-pattern)
* Content Source: [articles/logic-apps/logic-apps-create-api-app.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/logic-apps/logic-apps-create-api-app.md)
* Service: **logic-apps**
* GitHub Login: @ecfan
* Microsoft Alias: **estfan**

**Comment by wilcoblom** [comment]
Oh ja, btw... the email address on this page (customapishelp@microsoft.com) does not work...

**Comment by srvbpigh** [comment]
Hello, @wilcoblom
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @wilcoblom

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43599

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by wilcoblom** [comment]
The issue is closed?
What do you expect from me right now? I still have the issue, but the email address in the documentation is incorrect and a solution to my problem cannot be found...

Wilco
________________________________
