### ISSUE TITLE
Troubleshooter not working on Windows 2008R2

### ISSUE THREAD

**Issue by kevinrr3** [MicrosoftDocs/azure-docs.nl-nl#551]
The troubleshooter won't work on Windows 2008R2(And probably lower versions) because the Test-NetConnection CmdLet used in the troubleshooting script is not availible by default on these operating systems.
To workaround the issue you can copy the DnsClient,NetSecurity and NetTCPIP modules from a Windows 2012(Or higher) operating system to the modules folder("C:\Windows\System32\WindowsPowerShell\v1.0\Modules") of the Windows 2008R2 client's module folder.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c9e7b53a-a644-3ada-8363-ae4edc62f503
* Version Independent ID: a5567355-2edb-d722-3a08-2217d33d9510
* Content: [Understand the Windows agent check results in Azure Update Management](https://docs.microsoft.com/nl-nl/azure/automation/troubleshoot/update-agent-issues#feedback)
* Content Source: [articles/automation/troubleshoot/update-agent-issues.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/automation/troubleshoot/update-agent-issues.md)
* Service: **automation**
* Sub-service: **update-management**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by srvbpigh** [comment]
Hello, @kevinrr3
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kevinrr3 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43683

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
