### ISSUE TITLE
Typo's. A lot.

### ISSUE THREAD

**Issue by bramggcrypto** [MicrosoftDocs/azure-docs.nl-nl#552]
https://i.imgur.com/wZt4FA0.png

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c2e83171-fd05-9fe1-3ba7-0fb20161ee63
* Version Independent ID: 2e6b2451-5ff8-a277-90ea-49aa70957977
* Content: [Wat is Azure Active Directory Identity Protection?](https://docs.microsoft.com/nl-nl/azure/active-directory/identity-protection/overview-identity-protection#feedback)
* Content Source: [articles/active-directory/identity-protection/overview-identity-protection.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/identity-protection/overview-identity-protection.md)
* Service: **active-directory**
* Sub-service: **identity-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @bramggcrypto
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @bramggcrypto

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Microsoft DOCS International Team
Kind regards,
