### ISSUE TITLE
Availability tests Ip`s are outdated

### ISSUE THREAD

**Issue by tkrielaart** [MicrosoftDocs/azure-docs.nl-nl#554]
Today I was testing something in application insights. I noticed that not all the ip`s that are used by the availability test are mentioned in the page. Could this please be updated.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 92dd03db-51fc-ee03-3244-f0b847303b90
* Version Independent ID: 0794a496-ee0c-142d-b37c-a3482d24ffec
* Content: [IP-adressen die worden gebruikt door Application Insights en Log Analytics](https://docs.microsoft.com/nl-nl/azure/azure-monitor/app/ip-addresses#feedback)
* Content Source: [articles/azure-monitor/app/ip-addresses.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/azure-monitor/app/ip-addresses.md)
* Service: **azure-monitor**
* Sub-service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by tkrielaart** [comment]
Currently the following ip`s are missing:
20.40.129.49 -France?
52.158.28.85 -Ireland?
51.144.56.110 -amsterdam?
But there might be more.

**Comment by srvbpigh** [comment]
Hello, @tkrielaart
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mrbullwinkle** [comment]
@tkrielaart thanks for bringing this to our attention. I am pinging our SRE team now to confirm those addresses and any additional updates to the doc that may be needed. I will respond back to this thread once the doc is updated.

**Comment by CeciAc** [comment]
Hi team, 
I moved this issueto the en-US repo https://github.com/MicrosoftDocs/azure-docs/issues/43987

Kind regards
