### ISSUE TITLE
Make an api call available to automaticly keep up to date.

### ISSUE THREAD

**Issue by mvonck** [MicrosoftDocs/azure-docs.nl-nl#555]
Please provide an api that will help us to gather the full list of these ip addresses. This would be used to automate the changes.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 92dd03db-51fc-ee03-3244-f0b847303b90
* Version Independent ID: 0794a496-ee0c-142d-b37c-a3482d24ffec
* Content: [IP-adressen die worden gebruikt door Application Insights en Log Analytics](https://docs.microsoft.com/nl-nl/azure/azure-monitor/app/ip-addresses#outgoing-ports)
* Content Source: [articles/azure-monitor/app/ip-addresses.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/azure-monitor/app/ip-addresses.md)
* Service: **azure-monitor**
* Sub-service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by srvbpigh** [comment]
Hello, @mvonck
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mrbullwinkle** [comment]
@mvonck. Thank you for the feedback! I would recommend creating a uservoice request for this feature here: [https://feedback.azure.com/forums/357324-azure-monitor-application-insights?](https://feedback.azure.com/forums/357324-azure-monitor-application-insights?). We have had similar feedback come in a few times in the past via the docs, but we have never gotten enough requests for it to get traction. 

If you add this to the feedback forums please respond back to this thread with a link to your request and I would be happy to add an upvote.

**Comment by mvonck** [comment]
ok, i have found an existing request that i will vote on: 

https://feedback.azure.com/forums/357324-azure-monitor-application-insights/suggestions/36079819--service-tag-for-application-insights-whitelistin

**Comment by mrbullwinkle** [comment]
Excellent, thank you so much. I added my vote as well. I am going to close out this issue, since it isn't actionable from a docs perspective. Thank you again for your feedback!

**Comment by mrbullwinkle** [comment]
#please-close
