### ISSUE TITLE
Omgekeerde vertaling

### ISSUE THREAD

**Issue by k3ssen** [MicrosoftDocs/azure-docs.nl-nl#556]
Er zijn meerdere dingen verkeerd vertaald en sommige dingen moeten juist niet worden vertaald, zoals 'naam' onder function. json-eigenschappen. De meeste dingen lees je zo over heen, maar in het bijzonder is de volgende vertaling onhandig: 
"We raden u aan om runOnStartup in te stellen op true in productie."
Dit wordt namelijk juist afgeraden.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b5527c3b-a5da-c73d-66c2-20d96003ff7c
* Version Independent ID: 42154c7b-b0e0-26db-79bc-3f1673c48e40
* Content: [Timer trigger voor Azure Functions](https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-bindings-timer?tabs=csharp#feedback)
* Content Source: [articles/azure-functions/functions-bindings-timer.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/azure-functions/functions-bindings-timer.md)
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by srvbpigh** [comment]
Hello, @k3ssen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @k3ssen 
Hartelijk dank voor uw feedback. De opgevraagde pagina is automatisch vertaald. Dergelijke pagina's zijn niet altijd perfect leesbaar. We hebben onlangs aan de rechterkant een optie toegevoegd waarmee u de pagina in het Engels kunt lezen. U kunt dan omschakelen naar de Engelse versie zonder de taalinstellingen te wijzigen. 
Met vriendelijke groet, 
Het team van Microsoft DOCS International
