### ISSUE TITLE
Unreadable translation

### ISSUE THREAD

**Issue by mvreijn** [MicrosoftDocs/azure-docs.nl-nl#561]
This Dutch translation is so bad that the original meaning of most (important) sections is lost. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: faed3c33-d05e-7a05-1327-27a79325f677
* Version Independent ID: 151a61e3-ea34-7716-bbc8-66177f768b7b
* Content: [Azure AD Connect-synchronisatie: Filtering configureren](https://docs.microsoft.com/nl-nl/azure/active-directory/hybrid/how-to-connect-sync-configure-filtering#feedback)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sync-configure-filtering.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/hybrid/how-to-connect-sync-configure-filtering.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @mvreijn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @mvreijn
Hartelijk dank voor uw feedback. De opgevraagde pagina is automatisch vertaald. Dergelijke pagina's zijn niet altijd perfect leesbaar. We hebben onlangs aan de rechterkant een optie toegevoegd waarmee u de pagina in het Engels kunt lezen. U kunt dan omschakelen naar de Engelse versie zonder de taalinstellingen te wijzigen. 

Met vriendelijke groet, 
Het team van Microsoft DOCS International
