### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by PhilippeDevaux** [MicrosoftDocs/azure-docs.nl-nl#564]
In the Dutch version, chapter "Progressive Profiling, 2 underscores split a word in half.

current text: "(...) Met de progressieve profilering kunnen uw klanten snel hun eerste trans actie volt ooien door een minimale hoeveelheid informatie te verzamelen. (...)"

New corrected text: "(...) Met de progressieve profilering kunnen uw klanten snel hun eerste transactie voltooien door een minimale hoeveelheid informatie te verzamelen. (...)"

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 245ef8a4-a811-19b7-676c-aa9b82e2126f
* Version Independent ID: ad2ec743-2aa7-b3c7-3350-2986a78d7c90
* Content: [Wat is Azure Active Directory B2C?](https://docs.microsoft.com/nl-nl/azure/active-directory-b2c/active-directory-b2c-overview#feedback)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-overview.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory-b2c/active-directory-b2c-overview.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @mmacy
* Microsoft Alias: **marsma**

**Comment by srvbpigh** [comment]
Hello, @PhilippeDevaux
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @philippe-entringer 

Your contribution is much appreciated. The reported error was fixed for future releases but unfortunately, this page is not available anymore for nl-nl.

We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
