### ISSUE TITLE
managedIdentity

### ISSUE THREAD

**Issue by frankzo** [MicrosoftDocs/azure-docs.nl-nl#566]
When using a managedIdentity in ARM deployments "clientId" doest not work; objectID does work but cannot be abstracted from the deployment.

clientID should be "ApplicationId": since this is working and can be abstracted by using reference('vmresourceid', '2017-12-01', 'Full').identity.principalId]"

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 40aaccb8-19ba-168f-f5bf-65f1f5331541
* Version Independent ID: 6cdfd166-633a-50a3-2b45-cde0e991e540
* Content: [Aangepaste script extensie voor Azure voor Windows](https://docs.microsoft.com/nl-nl/azure/virtual-machines/extensions/custom-script-windows#feedback)
* Content Source: [articles/virtual-machines/extensions/custom-script-windows.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/virtual-machines/extensions/custom-script-windows.md)
* Service: **virtual-machines-windows**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by srvbpigh** [comment]
Hello, @frankzo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47799](https://github.com/MicrosoftDocs/azure-docs/issues/47799) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @frankzo,  

Uw bijdrage wordt enorm gewaardeerd. Uw feedback heeft betrekking op de oorspronkelijke documentatie.  

We migreren dit probleem daarom naar de Engelse opslagplaats. U kunt hier de status van het probleem controleren: https://github.com/MicrosoftDocs/azure-docs/issues/47799.  

We stellen uw bijdrage aan onze artikelen zeer op prijs.   

Met vriendelijke groet,  
Het team van Microsoft DOCS International
