### ISSUE TITLE
Unnecessary command listing in Script explanation

### ISSUE THREAD

**Issue by SteveVaneeckhout** [MicrosoftDocs/azure-docs.nl-nl#568]
Get-AzWebAppMetric is listed in the Script explanation section but is not used in the sample.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1c9f0745-8210-5e90-b12c-26bcc94ea4b8
* Version Independent ID: 59c114af-d3cf-c4b6-72bc-506a4047cb7c
* Content: [Power shell: monitor met webserver logboeken](https://docs.microsoft.com/nl-nl/azure/app-service/scripts/powershell-monitor?toc=%2fpowershell%2fmodule%2ftoc.json)
* Content Source: [articles/app-service/scripts/powershell-monitor.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/app-service/scripts/powershell-monitor.md)

**Comment by srvbpigh** [comment]
Hello, @SteveVaneeckhout
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49977](https://github.com/MicrosoftDocs/azure-docs/issues/49977) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @SteveVaneeckhout,  

Uw bijdrage wordt enorm gewaardeerd. Uw feedback heeft betrekking op de oorspronkelijke documentatie.  

We migreren dit probleem daarom naar de Engelse opslagplaats. U kunt hier de status van het probleem controleren: https://github.com/MicrosoftDocs/azure-docs/issues/49977.  

We stellen uw bijdrage aan onze artikelen zeer op prijs.   

Met vriendelijke groet,  
Het team van Microsoft DOCS International
