### ISSUE TITLE
App registrations (preview) error

### ISSUE THREAD

**Issue by dewitweb** [MicrosoftDocs/azure-docs.nl-nl#569]
When creating the app registration through preview i run into the following error: 

Failed to create  application. Error detail: Claim is invalid: offline_access does not exist in client application's RequiredResourceAccess. [Uhab4]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 45fe2896-2630-fcfa-97ed-c11f5bcdeb26
* Version Independent ID: fa30e08e-3f8e-0305-a061-6d3e74bbd5de
* Content: [Resources beheren met Microsoft Graph - Azure AD B2C](https://docs.microsoft.com/nl-nl/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-preview#feedback)
* Content Source: [articles/active-directory-b2c/microsoft-graph-get-started.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory-b2c/microsoft-graph-get-started.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @mmacy
* Microsoft Alias: **marsma**

**Comment by srvbpigh** [comment]
Hello, @dewitweb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by dewitweb** [comment]
Maybe this is because i was in the wrong section. The comment on issue #571 pointed me in the right direction.

**Comment by mmacy** [comment]
@dewitweb Sure thing, glad you got it sorted.

#please-close @CeciAc
