### ISSUE TITLE
when following "Grant API access", version: Applications

### ISSUE THREAD

**Issue by dewitweb** [MicrosoftDocs/azure-docs.nl-nl#570]
1) There is no "settings"
2) there is no "required permissions"

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 45fe2896-2630-fcfa-97ed-c11f5bcdeb26
* Version Independent ID: fa30e08e-3f8e-0305-a061-6d3e74bbd5de
* Content: [Resources beheren met Microsoft Graph - Azure AD B2C](https://docs.microsoft.com/nl-nl/azure/active-directory-b2c/microsoft-graph-get-started?tabs=applications#feedback)
* Content Source: [articles/active-directory-b2c/microsoft-graph-get-started.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory-b2c/microsoft-graph-get-started.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @mmacy
* Microsoft Alias: **marsma**

**Comment by srvbpigh** [comment]
Hello, @dewitweb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mmacy** [comment]
Hello @dewitweb, please ensure that you've selected **Active Directory** > **App registrations (Legacy)** as specified in the steps:

![image](https://user-images.githubusercontent.com/13394541/75461771-185cd880-5938-11ea-9257-c118bd307f17.png)

With Active Directory (_not_ Azure AD B2C) selected (but still in your B2C tenant), you select **App registrations (Legacy)**:

![image](https://user-images.githubusercontent.com/13394541/75461908-47734a00-5938-11ea-9c05-1e9fb588e7de.png)

You then have **Settings** > **API Access** > **Required permissions** available:

![image](https://user-images.githubusercontent.com/13394541/75462110-90c39980-5938-11ea-90a9-e2df85a32445.png)

**Comment by dewitweb** [comment]
Doh. Switching between the tenants got me confused. 

Thanks for pointing this out.

**Comment by mmacy** [comment]
@dewitweb Sure thing! We're certainly aware that the tenant and context (AD vs. B2C) switching is a common source of confusion. The "Applications" and "App registrations (Preview)" situation will improved once the new _App registrations_ goes GA, after which only a single option will be available in the portal and presented in the docs. We'll continue to work on simplifying the experience, this being one of the first pieces.

#please-close
