### ISSUE TITLE
"Under API ACCESS, select Keys"

### ISSUE THREAD

**Issue by dewitweb** [MicrosoftDocs/azure-docs.nl-nl#571]
Keys are not under "API ACCESS" but under "General"

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 45fe2896-2630-fcfa-97ed-c11f5bcdeb26
* Version Independent ID: fa30e08e-3f8e-0305-a061-6d3e74bbd5de
* Content: [Resources beheren met Microsoft Graph - Azure AD B2C](https://docs.microsoft.com/nl-nl/azure/active-directory-b2c/microsoft-graph-get-started?tabs=applications#feedback)
* Content Source: [articles/active-directory-b2c/microsoft-graph-get-started.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory-b2c/microsoft-graph-get-started.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @mmacy
* Microsoft Alias: **marsma**

**Comment by dewitweb** [comment]
version: Applications

**Comment by srvbpigh** [comment]
Hello, @dewitweb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mmacy** [comment]
Hi @dewitweb, this is related to #570 - please ensure you are in **Active Directory** > **App registrations (Legacy)** as specified in the steps. If you've registered your application as specified, **Keys** appears under **API Access**:

![image](https://user-images.githubusercontent.com/13394541/75462689-76d68680-5939-11ea-8234-7c79e42668b1.png)

**Comment by dewitweb** [comment]
Thanks. Same as in #571 i guess. Swithcing between tenants and the same kind of options in B2C tenant, host tenant and again in B2c settings got me confused.

**Comment by mmacy** [comment]
@dewitweb Sure thing, glad you got it sorted.

#please-close @CeciAc
