### ISSUE TITLE
Poor (auto-)translation / slechte vertaling

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/azure-docs.nl-nl#572]
De vertaling is zo slecht dat sommige delen nauwelijks meer te begrijpen zijn.
Ook zijn de afbreekregels (hyphenation) op merkwaardige wijze in de war. Diverse woorden en namen worden midden in een regel afgebroken.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c2e83171-fd05-9fe1-3ba7-0fb20161ee63
* Version Independent ID: 2e6b2451-5ff8-a277-90ea-49aa70957977
* Content: [Wat is Azure Active Directory Identity Protection?](https://docs.microsoft.com/nl-nl/azure/active-directory/identity-protection/overview-identity-protection#feedback)
* Content Source: [articles/active-directory/identity-protection/overview-identity-protection.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/identity-protection/overview-identity-protection.md)
* Service: **active-directory**
* Sub-service: **identity-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @Rvvhub
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hallo, @Rvvhub ,

Hartelijk dank voor uw feedback. 

De opgevraagde pagina is automatisch vertaald. Dergelijke pagina's zijn niet altijd perfect leesbaar. We hebben onlangs aan de rechterkant een optie toegevoegd waarmee u de pagina in het Engels kunt lezen. 

U kunt dan omschakelen naar de Engelse versie zonder de taalinstellingen te wijzigen.

Met vriendelijke groet,
Het team van Microsoft DOCS International
