### ISSUE TITLE
please add new VM types

### ISSUE THREAD

**Issue by dvherk** [MicrosoftDocs/azure-docs.nl-nl#573]
example, but likely more you can and hence should add;
https://azure.microsoft.com/nl-nl/blog/announcing-new-amd-epyc-based-azure-virtual-machines/

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 568a0854-5b9e-0d79-642f-2775271d0521
* Version Independent ID: 876df17a-3a80-8e2d-bb70-c6810df7fd18
* Content: [Overzicht van de Azure Compute-eenheid](https://docs.microsoft.com/nl-nl/azure/virtual-machines/acu?toc=%2Fazure%2Fvirtual-machines%2Fwindows%2Ftoc.json&bc=%2Fazure%2Fvirtual-machines%2Fwindows%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [articles/virtual-machines/acu.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/virtual-machines/acu.md)
* Service: **virtual-machines**
* GitHub Login: @mimckitt
* Microsoft Alias: **jonbeck**

**Comment by srvbpigh** [comment]
Hello, @dvherk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49892](https://github.com/MicrosoftDocs/azure-docs/issues/49892) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @dvherk,  

Uw bijdrage wordt enorm gewaardeerd. Uw feedback heeft betrekking op de oorspronkelijke documentatie.  

We migreren dit probleem daarom naar de Engelse opslagplaats. U kunt hier de status van het probleem controleren: https://github.com/MicrosoftDocs/azure-docs/issues/49892.  

We stellen uw bijdrage aan onze artikelen zeer op prijs.   

Met vriendelijke groet,  
Het team van Microsoft DOCS International
