### ISSUE TITLE
Page is shown in Table storage section but AzCopy cannot be used for Table Storage

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/azure-docs.nl-nl#574]
This page is shown in the section about data transfer for `Table storage` but the documented / supported version version of `AzCopy` cannot be used for `Table Storage`, which is very confusing.

It is written that you have to revert to `AzCopy 7.3` to use it with `Table Storage` but it is not documented how to use that version for `Table Storage`:
> If you want to copy data to and from your Azure Table storage service, then install AzCopy version 7.3.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 15911160-5ba2-fb0a-0b24-16b3857e20ce
* Version Independent ID: d925bc9f-f825-2f82-168c-6c30d716b9ce
* Content: [Gegevens kopiëren of verplaatsen naar Azure Storage met behulp van AzCopy V10 toevoegen](https://docs.microsoft.com/nl-nl/azure/storage/common/storage-use-azcopy-v10?toc=%2fazure%2fstorage%2ftables%2ftoc.json)
* Content Source: [articles/storage/common/storage-use-azcopy-v10.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/storage/common/storage-use-azcopy-v10.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by srvbpigh** [comment]
Hello, @hansmbakker
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49861](https://github.com/MicrosoftDocs/azure-docs/issues/49861) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @hansmbakker, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/49861. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by hansmbakker** [comment]
Yes, thank you @CeciAc / @srvbpigh !
