### ISSUE TITLE
Vertaal Issue

### ISSUE THREAD

**Issue by AzureStackNerd** [MicrosoftDocs/azure-docs.nl-nl#577]
Wrong: "Playbooks worden gecodeerd met behulp van YAML, zodat ze niet kunnen worden gelezen."
--
"Playbooks are coded using YAML so as to be human-readable."  --&gt;
"Playbooks worden geschreven in YAML, zodat deze makkelijk door mensen kunnen worden gelezen."

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 54d793fc-86e3-ff1c-c06a-2a77df00e983
* Version Independent ID: 4c134f4c-a4a1-7675-4d10-f8e7786d46ed
* Content: [Ansible gebruiken met Azure](https://docs.microsoft.com/nl-nl/azure/ansible/ansible-overview#feedback)
* Content Source: [articles/ansible/ansible-overview.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/ansible/ansible-overview.md)

**Comment by srvbpigh** [comment]
Hello, @AzureStackNerd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo @AzureStackNerd

Bedankt voor uw bijdrage.

Bijdragen op vertaalproblemen voor inhoud die door machines is vertaald worden momenteel niet geaccepteerd.

We waarderen uw feedback over en suggesties voor onze door mensen vertaalde inhoud. Deze gegevens worden gebruikt om de machine translation-engines te trainen. Dus uw bijdragen verbeteren de kwaliteit van zowel door mensen als door machines uitgevoerde vertalingen.

Door mensen vertaalde onderwerpen kunnen worden onderscheiden van door machines vertaalde onderwerpen door de ms.translationtype-metagegevenswaarde 'HT' (in tegenstelling tot 'MT' voor door machines vertaald) in de koptekst van elk inhoudsbestand.

Bedankt voor uw bijdrage.

Het team van Microsoft DOCS Global Experience
