### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SuperDJ** [MicrosoftDocs/azure-docs.nl-nl#580]
In the title it states "micro soft" instead of "microsoft"
---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0ac43307-75d4-cb6f-e561-0dd9008f28c6
* Version Independent ID: 8fc47e76-5ee1-6aeb-73e2-c64c44e3e4ed
* Content: [Scopes, machtigingen en toestemming van micro soft Identity platform](https://docs.microsoft.com/nl-nl/azure/active-directory/develop/v2-permissions-and-consent#feedback)
* Content Source: [articles/active-directory/develop/v2-permissions-and-consent.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/develop/v2-permissions-and-consent.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @SuperDJ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @SuperDJ , 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings. 

Kind regards, 

Microsoft DOCS International Team
