### ISSUE TITLE
Capital letter is omitted

### ISSUE THREAD

**Issue by PhilippeDevaux** [MicrosoftDocs/azure-docs.nl-nl#582]
In several sentences the term "Azure AD" is used, but in other sentences the term "azure AD" is used. This is not conform.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: faed3c33-d05e-7a05-1327-27a79325f677
* Version Independent ID: 151a61e3-ea34-7716-bbc8-66177f768b7b
* Content: [Azure AD Connect synchronisatie: filteren configureren](https://docs.microsoft.com/nl-nl/azure/active-directory/hybrid/how-to-connect-sync-configure-filtering#filtering-options)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sync-configure-filtering.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/hybrid/how-to-connect-sync-configure-filtering.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @PhilippeDevaux
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @PhilippeDevaux 

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
