### ISSUE TITLE
commandline parameters for scale are incorrect

### ISSUE THREAD

**Issue by bartjanson** [MicrosoftDocs/azure-docs.nl-nl#583]
az aks nodepool scale parameters are different than stated above, the nodepool should be given with --name, the clustername should be given with --cluster-name, can this be changed above?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f41a301e-1baf-984d-74d7-bfaf7156eadf
* Version Independent ID: 6a92992b-0514-e969-025b-7071322b6ee4
* Content: [Een AKS-cluster (Azure Kubernetes Service) schalen](https://docs.microsoft.com/nl-nl/azure/aks/scale-cluster)
* Content Source: [articles/aks/scale-cluster.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/aks/scale-cluster.md)
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by srvbpigh** [comment]
Hello, @bartjanson
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @bartjanson , 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings. 

Kind regards, 

Microsoft DOCS International Team

**Comment by bartjanson** [comment]
But.. this isn't about the machine-translation, it is about the exact names of the arguments used in the code-samples. Even in the original english text, the commandline-parameters for specifying the nodepool and the cluster are not what the azure cli 'az aks nodepool scale' command has documented.
