### ISSUE TITLE
Difference between static website and blob container integration with CDN

### ISSUE THREAD

**Issue by Boosten** [MicrosoftDocs/azure-docs.nl-nl#589]
There are two options to make your blob container accessible via a CDN:

1) Mapping the blob container url to your CDN: https://docs.microsoft.com/nl-nl/azure/cdn/cdn-create-a-storage-account-with-cdn. 

Example configuration of a CDN endpoint: 
- Origin type: Storage
- Origin hostname: NAME.blob.core.windows.net
- Origin host header: NAME.blob.core.windows.net
- Origin path: /www (your blob container name)

2) Mapping the $web blob container "static website" url to your CDN:  https://docs.microsoft.com/nl-nl/azure/storage/blobs/static-website-content-delivery-network
In this scenario you need to enable the "static website" option on your storage account.

Example configuration of a CDN endpoint: 
- Origin type: Custom Origin
- Origin hostname: NAME.z6.web.core.windows.net (my static website public url)
- Origin host header: NAME.z6.blob.core.windows.net ((my static website public url)
- Origin path: (empty)

In the end, both are doing the same: mapping a blob container to a CDN endpoint. But option 2 seems redundant because we do not necessarily need the static website endpoint. 

I'm I missing something here :-)?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 8772b2a5-6b28-9d91-5fd4-e125d85126c6
* Version Independent ID: 0a58807a-e274-7833-7845-bed7ebaaf1bc
* Content: [Een statische website integreren met Azure CDN-Azure Storage](https://docs.microsoft.com/nl-nl/azure/storage/blobs/static-website-content-delivery-network)
* Content Source: [articles/storage/blobs/static-website-content-delivery-network.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/storage/blobs/static-website-content-delivery-network.md)
* Service: **storage**
* Sub-service: **blobs**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by srvbpigh** [comment]
Hello, @Boosten
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54024](https://github.com/MicrosoftDocs/azure-docs/issues/54024) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Boosten, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54024. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
