### ISSUE TITLE
Reusing responses is not supported?

### ISSUE THREAD

**Issue by LockTar** [MicrosoftDocs/azure-docs.nl-nl#590]
If you read the following documentation about spec (in particular section "Reusing Responses"):
https://swagger.io/docs/specification/describing-responses/

You can define responses separately that are equal for multiple operations. But if you upload that spec then new schemas will be generated. This will result in multiple responses that are the same. 

If you don't use components/responses but if you copy the responses by every operation. It will be fine. The schema (body of the response) will work when you put that in components/schemas section.

So this will work (response by operation):

```
description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
```

This will **not** work (will result in multiple `Error` schemas):

```
paths:
  /users:
    get:
      summary: Gets a list of users.
      response:        
        '401':
          $ref: '#/components/responses/Unauthorized'   # <-----
  /users/{id}:
    get:
      summary: Gets a user by ID.
      response:        
        '401':
          $ref: '#/components/responses/Unauthorized'   # <-----
# Descriptions of common components
components:
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
```

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: be16b5c5-40c4-3e6c-0b0d-840373c63f9f
* Version Independent ID: ced6b3ba-8da1-dd3d-9d1c-8a21dabd44fe
* Content: [Beperkingen en Details van de ondersteuning van API-indelingen - Azure API Management](https://docs.microsoft.com/nl-nl/azure/api-management/api-management-api-import-restrictions#feedback)
* Content Source: [articles/api-management/api-management-api-import-restrictions.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/api-management/api-management-api-import-restrictions.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by srvbpigh** [comment]
Hello, @LockTar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by LockTar** [comment]
Updated original post with more information.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54896](https://github.com/MicrosoftDocs/azure-docs/issues/54896) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @LockTar, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54896. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
