### ISSUE TITLE
Spelfout

### ISSUE THREAD

**Issue by tomgelmers** [MicrosoftDocs/azure-docs.nl-nl#592]
Spelfout op de eerste regel: "Azure Active Directory (Azure AD) is de cloud-gebaseerde service voor identiteits-en toegangs beheer van micro soft..."
micro soft -&gt; microsoft

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 278fd397-b3b7-5192-47ff-b5c9edfa44b4
* Version Independent ID: 9ca42ebd-4ff2-226f-8bae-74fc8973a825
* Content: [What is Azure Active Directory? (Engelstalig) - Azure Active Directory](https://docs.microsoft.com/nl-nl/azure/active-directory/fundamentals/active-directory-whatis#feedback)
* Content Source: [articles/active-directory/fundamentals/active-directory-whatis.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/fundamentals/active-directory-whatis.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @msaburnley
* Microsoft Alias: **ajburnle**

**Comment by srvbpigh** [comment]
Hello, @tomgelmers
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo @tomgelmers 

Bedankt voor uw bijdrage. 

Bijdragen op vertaalproblemen voor inhoud die door machines is vertaald worden momenteel niet geaccepteerd. 

We waarderen uw feedback over en suggesties voor onze door mensen vertaalde inhoud. Deze gegevens worden gebruikt om de machine translation-engines te trainen. Dus uw bijdragen verbeteren de kwaliteit van zowel door mensen als door machines uitgevoerde vertalingen. 

Door mensen vertaalde onderwerpen kunnen worden onderscheiden van door machines vertaalde onderwerpen door de ms.translationtype-metagegevenswaarde 'HT' (in tegenstelling tot 'MT' voor door machines vertaald) in de koptekst van elk inhoudsbestand. 

Bedankt voor uw bijdrage. 

Het team van Microsoft DOCS Global Experience
