### ISSUE TITLE
Azcopy update

### ISSUE THREAD

**Issue by sqlenders** [MicrosoftDocs/azure-docs.nl-nl#593]
Please add a parameter update so that AzCopy can update itselfs.
Like AzCopy update

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 15911160-5ba2-fb0a-0b24-16b3857e20ce
* Version Independent ID: d925bc9f-f825-2f82-168c-6c30d716b9ce
* Content: [Gegevens kopiëren of verplaatsen naar Azure Storage met behulp van AzCopy V10 toevoegen](https://docs.microsoft.com/nl-nl/azure/storage/common/storage-use-azcopy-v10)
* Content Source: [articles/storage/common/storage-use-azcopy-v10.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/storage/common/storage-use-azcopy-v10.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by srvbpigh** [comment]
Hello, @sqlenders
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @sqlenders , 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @sqlenders , 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @sqlenders , 

Thanks once again for your comment. 

Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future. 

Kind regards, 

Microsoft DOCS International Team
