### ISSUE TITLE
arm32v7 build failes

### ISSUE THREAD

**Issue by Bengkel** [MicrosoftDocs/azure-docs.nl-nl#602]
I tried to use the Azure IoT Task to in my Azure DevOps CI Pipeline. The purpose is to build a container image for arm32v7.

 I have selected a Unbuntu-18.04 Build Agent.

The build succeeds when I build an amd64 image; the build fails when I try to build an arm32v7 image.

Step 4/12 dotnet restore throws an exception:

```
standard_init_linux.go:211: exec user process caused "exec format error"

ERROR: The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

##[error]Error: The process '/usr/local/bin/iotedgedev' failed with exit code 1
```

Also the example on https://docs.microsoft.com/en-us/azure/iot-edge/how-to-devops-project does not build arm32v7 images.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 5098fbad-7df5-7c62-9d56-6e9646b86d0c
* Version Independent ID: 14e2f627-2215-4373-1071-7698bcc9354d
* Content: [CI/CD-pijp lijn met Azure DevOps Projects-Azure IoT Edge](https://docs.microsoft.com/nl-nl/azure/iot-edge/how-to-devops-project)
* Content Source: [articles/iot-edge/how-to-devops-project.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/iot-edge/how-to-devops-project.md)
* Service: **iot-edge**
* GitHub Login: @shizn
* Microsoft Alias: **xshi**

**Comment by srvbpigh** [comment]
Hello, @Bengkel
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #56984](https://github.com/MicrosoftDocs/azure-docs/issues/56984) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Bengkel, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/56984. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
