### ISSUE TITLE
Outdated BlockBlobService

### ISSUE THREAD

**Issue by sjoerdbroos1996** [MicrosoftDocs/azure-docs.nl-nl#653]
I would suggest to update the example as it's still using the BlockBlobService instead of the BlobServiceClient. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 26752b49-023e-da0d-a209-1eed0d7fcd25
* Version Independent ID: e43d7001-e9ce-a863-7456-fc28bb349736
* Content: [Quickstart: de Python-API gebruiken om een Azure Batch-taak uit te voeren - Azure Batch](https://docs.microsoft.com/nl-nl/azure/batch/quick-run-python)
* Content Source: [articles/batch/quick-run-python.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/batch/quick-run-python.md)
* Service: **batch**
* GitHub Login: @JnHs
* Microsoft Alias: **jenhayes**

**Comment by JnHs** [comment]
Hi @sjoerdbroos1996 - thank you for raising this issue, and apologies for the very long time to respond. The example has now been updated to remove BlockBlobService. I'm going to close this issue now - thanks again for taking the time to share your feedback!
#please-close
