### ISSUE TITLE
how long

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/azure-docs.nl-nl#659]
So, how long does does it take to encrypt a restored machine. It would be great if that info was addes to this page

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 54252e63-be57-2c49-15fc-b9dc7fdda1b3
* Version Independent ID: 30777b2a-604d-ce18-c891-4d272632f039
* Content: [Back-up en herstel van versleutelde virtuele Azure-machines - Azure Backup](https://docs.microsoft.com/nl-nl/azure/backup/backup-azure-vms-encryption)
* Content Source: [articles/backup/backup-azure-vms-encryption.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/backup/backup-azure-vms-encryption.md)
* Service: **backup**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
#reassign:v-amallick

**Comment by dcurwin** [comment]
@v-amallick - Please address this issue.

**Comment by dcurwin** [comment]
#reassign:v-amallick

**Comment by v-amallick** [comment]
@WillemVerwijs: Thank you for bringing it to our notice. Will check with the product group and get back.

@dcurwin: Thank you for assigning.

**Comment by v-amallick** [comment]
@WillemVerwijs: As a machine already stays encrypted when you restore, it is not needed to encrypt it manually. So, time to encrypt a restored machine is not applicable.

If you have any queries, please get back to us. We will be happy to help you.

Thank you.

**Comment by v-amallick** [comment]
#please-close

**Comment by dcurwin** [comment]
@SunnyDeng - Can you help close this?

**Comment by SunnyDeng** [comment]
enabled the loc pipeline for nl-nl.
