### ISSUE TITLE
Vertaling

### ISSUE THREAD

**Issue by MarceluitNL** [MicrosoftDocs/azure-docs.nl-nl#71]
Beste Microsoft, 
Ik begrijp dat jullie hard werken aan goede automatische vertalingen.
Helaas vind ik de automatische vertaling een beetje teleurstellend.
Ik had moeite om me goed door dit artikel heen te werken, doordat er op diverse plaatsen woorden ontbreken en/of dat er verkeerd is vervoegd.
Met vriendelijke groeten,
Marcel

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: bfe0b26e-f030-6630-bc2c-5344d61a8018
* Version Independent ID: c181d839-265d-a874-943c-5974637d86d3
* Content: [Microsoft Authenticator-app help en ondersteuning](https://docs.microsoft.com/nl-nl/azure/multi-factor-authentication/end-user/microsoft-authenticator-app-faq)
* Content Source: [articles/multi-factor-authentication/end-user/microsoft-authenticator-app-faq.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/multi-factor-authentication/end-user/microsoft-authenticator-app-faq.md)
* Service: **multi-factor-authentication**
* Product: **unspecified**
* GitHub Login: @barlanmsft
* Microsoft Alias: **lizross**

**Comment by CeciAc** [comment]
Hallo, @MarceluitNL 

Hartelijk dank voor uw feedback. De opgevraagde pagina is automatisch vertaald. Dergelijke pagina's zijn niet altijd perfect leesbaar. We hebben onlangs aan de rechterkant een optie toegevoegd waarmee u de pagina in het Engels kunt lezen. U kunt dan omschakelen naar de Engelse versie zonder de taalinstellingen te wijzigen. 

Met vriendelijke groet, 

Het team van Microsoft DOCS International
