### ISSUE TITLE
Taal

### ISSUE THREAD

**Issue by madv113** [MicrosoftDocs/azure-docs.nl-nl#74]
Waarom kan ik geen engels kiezen of waarom kan ik niet in een muisklik naar het orgineel? Alleen als je de muis over de tekst haalt krijg je de engelse tekst te zien. Dit leest erg vervelend! 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a8a0ac96-e410-b481-9fdb-90d827a98935
* Version Independent ID: 6a133cdf-a66a-9807-d431-2e0ae43b253b
* Content: [Overzicht van Azure Functions](https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-overview)
* Content Source: [articles/azure-functions/functions-overview.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-functions/functions-overview.md)
* Service: **functions**
* GitHub Login: @mattchenderson
* Microsoft Alias: **glenga**

**Comment by gosali** [comment]
Hello, @madv113, 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings. 

![image](https://user-images.githubusercontent.com/16022575/41796008-29c03ad6-763b-11e8-9901-447e3f61ca8b.png) 

Kind regards, 

Microsoft DOCS International Team

**Comment by joostvz** [comment]
@madv113 Er zit rechtsboven een slider "Lezen in het Engels". Als je de slider overhaalt is alle tekst in het Engels.

**Comment by CeciAc** [comment]
Hallo, @madv113
Hartelijk dank voor uw feedback. De opgevraagde pagina is automatisch vertaald. Dergelijke pagina's zijn niet altijd perfect leesbaar. We hebben onlangs aan de rechterkant een optie toegevoegd waarmee u de pagina in het Engels kunt lezen. U kunt dan omschakelen naar de Engelse versie zonder de taalinstellingen te wijzigen. 

Met vriendelijke groet, 

Het team van Microsoft DOCS International

**Comment by madv113** [comment]
I wish you do that for all Microsoft site s

Best regards
Marcel

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________
