### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by whaakman** [MicrosoftDocs/azure-docs.nl-nl#75]
requirements.txt is not present in the repository. You are required to install Flask by yourself (pip install -U Flask).

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ac1cd213-5a9f-ae10-73b5-96061bfbd9d9
* Version Independent ID: cec78ca0-f4c0-970e-dde0-44db72d3819f
* Content: [Een Python-web-app maken in Azure](https://docs.microsoft.com/nl-nl/azure/app-service/app-service-web-get-started-python)
* Content Source: [articles/app-service/app-service-web-get-started-python.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/app-service/app-service-web-get-started-python.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin;cfowler**

**Comment by cephalin** [comment]
@whaakman This article has been retired and the replacement is at https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python. Please use that instead. It looks like the change hasn't been replicated in your language. #please-close

**Comment by whaakman** [comment]
@cephalin I have read the article but wasn't aware that this is the replace article. Thanks.
