### ISSUE TITLE
PowerShell Support

### ISSUE THREAD

**Issue by JulienFloris** [MicrosoftDocs/azure-docs.nl-nl#76]
When Will PowerShell support be added?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: d90bbf62-44f9-30a6-d6ea-bbf776f6efc5
* Version Independent ID: b3961eac-6c70-b345-f48c-e4c0ec67059c
* Content: [Azure App Service IP-beperkingen](https://docs.microsoft.com/nl-nl/azure/app-service/app-service-ip-restrictions)
* Content Source: [articles/app-service/app-service-ip-restrictions.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/app-service/app-service-ip-restrictions.md)
* Service: **app-service-web**
* GitHub Login: @btardif
* Microsoft Alias: **byvinyal**

**Comment by LisandroSu** [comment]
Hello, @JulienFloris

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
