### ISSUE TITLE
Stop translating documentation

### ISSUE THREAD

**Issue by rthewhite** [MicrosoftDocs/azure-docs.nl-nl#77]
Everytime i go to the documentation here, it get's auto translated to my native language Dutch. 
That doesn't make sense at all, all the technical terms are translated as well and it becomes utter useless.....

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7d575e82-637b-32de-e64d-75adf4b6d976
* Version Independent ID: e346a973-fcb9-0c10-c1ed-17acd806ced9
* Content: [Triggers en bindingen in Azure Functions](https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-triggers-bindings#feedback)
* Content Source: [articles/azure-functions/functions-triggers-bindings.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-functions/functions-triggers-bindings.md)
* Service: **functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by LisandroSu** [comment]
Hello, @rthewhite , 
 
Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings. 
 
Kind regards, 
Microsoft DOCS International Team
