### ISSUE TITLE
Document has some MD file syntax errors

### ISSUE THREAD

**Issue by JimmyBandell** [MicrosoftDocs/azure-docs.nl-nl#78]
Hi i think there is missing a hard return in the md file for the table under:
https://docs.microsoft.com/nl-nl/azure/storage/files/storage-sync-files-firewall-and-proxy?WT.mc_id=email#firewall
Because is see the following in the document:

| Region | Primary endpoint URL | Paired region | Discovery URL | |--------|---------------------------------------||--------||---------------------------------------| | Australia East | https://kailani-aue.one.microsoft.com | Australia Souteast | https://kailani-aue.one.microsoft.com | | Australia Southeast | https://kailani-aus.one.microsoft.com | Australia East | https://tm-kailani-aus.one.microsoft.com | | Canada Central | https://kailani-cac.one.microsoft.com | Canada East | https://tm-kailani-cac.one.microsoft.com | | Canada East | https://kailani-cae.one.microsoft.com | Canada Central | https://tm-kailani.cae.one.microsoft.com | | Central US | https://kailani-cus.one.microsoft.com | East US 2 | https://tm-kailani-cus.one.microsoft.com | | East Asia | https://kailani11.one.microsoft.com | Southeast Asia | https://tm-kailani11.one.microsoft.com | | East US | https://kailani1.one.microsoft.com | West US | https://tm-kailani1.one.microsoft.com | | East US 2 | https://kailani-ess.one.microsoft.com | Central US | https://tm-kailani-ess.one.microsoft.com | | North Europe | https://kailani7.one.microsoft.com | West Europe | https://tm-kailani7.one.microsoft.com | | Southeast Asia | https://kailani10.one.microsoft.com | East Asia | https://tm-kailani10.one.microsoft.com | | UK South | https://kailani-uks.one.microsoft.com | UK West | https://tm-kailani-uks.one.microsoft.com | | UK West | https://kailani-ukw.one.microsoft.com | UK South | https://tm-kailani-ukw.one.microsoft.com | | West Europe | https://kailani6.one.microsoft.com | North Europe | https://tm-kailani6.one.microsoft.com | | West US | https://kailani.one.microsoft.com | East US | https://tm-kailani.one.microsoft.com |

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: e517794d-c237-f052-8445-0280c2ba9ecd
* Version Independent ID: 36721ebd-be22-f1e6-882a-83f6d54a1b12
* Content: [Azure File Sync on-premises firewall en proxy-instellingen](https://docs.microsoft.com/nl-nl/azure/storage/files/storage-sync-files-firewall-and-proxy?WT.mc_id=email#firewall)
* Content Source: [articles/storage/files/storage-sync-files-firewall-and-proxy.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/storage/files/storage-sync-files-firewall-and-proxy.md)
* Service: **storage**
* GitHub Login: @fauhse
* Microsoft Alias: **fauhse**

**Comment by gosali** [comment]
Hello, @JimmyBandell , 

 Thank you for your feedback.   
We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JimmyBandell ,
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. The bug was properly escalated due to a broken symbol near the table that gets the format broken after the side by side process.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
