### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by bartmcleod** [MicrosoftDocs/azure-docs.nl-nl#81]
What if I update the container image and I push the new image to the repository, how can I make sure the new image is picked up by the application?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f970943e-c7b4-919c-65ea-6ba20831e74d
* Version Independent ID: 90c5dd06-ea6d-7af8-f88c-9d189e9ceef2
* Content: [Een aangepaste Docker-installatiekopie gebruiken voor Web App for Containers - Azure](https://docs.microsoft.com/nl-nl/azure/app-service/containers/tutorial-custom-docker-image#use-a-docker-image-from-any-private-registry-optional)
* Content Source: [articles/app-service/containers/tutorial-custom-docker-image.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/app-service/containers/tutorial-custom-docker-image.md)
* Service: **app-service**
* GitHub Login: @SyntaxC4
* Microsoft Alias: **cfowler**

**Comment by LisandroSu** [comment]
Hello, @bartmcleod 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
