### ISSUE TITLE
Container App service / Web app does not map port 2222

### ISSUE THREAD

**Issue by bartmcleod** [MicrosoftDocs/azure-docs.nl-nl#83]
I cannot SSH into my custom container, because the run command that Azure uses, does not publish port 2222 with '-p 2222:2222'. When I run the same command locally and _add_ the port mapping that publishes the exposed port, then I can login using SSH. I cannot find documentation on how to influence the run command being used.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1b4f27ae-bfd4-6663-13ce-c3d0b40326e3
* Version Independent ID: 892091ad-f470-d715-ac5b-6b487640a88e
* Content: [SSH-ondersteuning voor Azure App Service on Linux](https://docs.microsoft.com/nl-nl/azure/app-service/containers/app-service-linux-ssh-support)
* Content Source: [articles/app-service/containers/app-service-linux-ssh-support.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/app-service/containers/app-service-linux-ssh-support.md)
* Service: **app-service**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by LisandroSu** [comment]
Hello, @bartmcleod 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
