### ISSUE TITLE
Wrong syntax highlighting / code block

### ISSUE THREAD

**Issue by bartmcleod** [MicrosoftDocs/azure-docs.nl-nl#84]
This block should be edited to be a proper code block (backticks are wrong):
```docker
COPY startup /opt/startup
...
RUN chmod 755 /opt/startup/init_container.sh
...
ENTRYPOINT ["/opt/startup/init_container.sh"]
```

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1b4f27ae-bfd4-6663-13ce-c3d0b40326e3
* Version Independent ID: 892091ad-f470-d715-ac5b-6b487640a88e
* Content: [SSH-ondersteuning voor Azure App Service on Linux](https://docs.microsoft.com/nl-nl/azure/app-service/containers/app-service-linux-ssh-support)
* Content Source: [articles/app-service/containers/app-service-linux-ssh-support.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/app-service/containers/app-service-linux-ssh-support.md)
* Service: **app-service**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by wesmc7777** [comment]
@bartmcleod Fixed. Thank you!

**Comment by LisandroSu** [comment]
Hello, @bartmcleod ,
 
Thank you for your feedback.
