### ISSUE TITLE
Powershell support for Capture config

### ISSUE THREAD

**Issue by acjoskam** [MicrosoftDocs/azure-docs.nl-nl#85]
Is enabling EH Capture using Powershell coming any time soon?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 71093e2a-bbff-3a79-5f16-289a3a5f6cd7
* Version Independent ID: e4e9873d-0ae7-25a4-16d1-5ecac6e84b91
* Content: [Overzicht van Azure Eventhubs Capture](https://docs.microsoft.com/nl-nl/azure/event-hubs/event-hubs-capture-overview)
* Content Source: [articles/event-hubs/event-hubs-capture-overview.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/event-hubs/event-hubs-capture-overview.md)
* Service: **event-hubs**
* GitHub Login: @ShubhaVijayasarathy
* Microsoft Alias: **shvija**

**Comment by LisandroSu** [comment]
Hello, @acjoskam 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
