### ISSUE TITLE
Azure DevOps (VSTS) has no UploadArtifact parameter

### ISSUE THREAD

**Issue by rfcdejong** [MicrosoftDocs/azure-docs.nl-nl#87]
I don't see an easy way to use DSC from a release pipeline, cause the Deploy ARM template task has no UploadArtifact parameter. I could use an own powershell or find another way, but wanted to use it like this. Any idea?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 627bf595-d3a1-bbdd-b045-b6c4a580fdb3
* Version Independent ID: 529fbe9a-c711-c1a0-5697-5853b1e51071
* Content: [Desired State Configuration voor een overzicht van Azure](https://docs.microsoft.com/nl-nl/azure/virtual-machines/extensions/dsc-overview)
* Content Source: [articles/virtual-machines/extensions/dsc-overview.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/virtual-machines/extensions/dsc-overview.md)
* Service: **virtual-machines-windows**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by LisandroSu** [comment]
Hello, @rfcdejong ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
