### ISSUE TITLE
E-mail notifications on alert

### ISSUE THREAD

**Issue by sebastiaanvroom** [MicrosoftDocs/azure-docs.nl-nl#95]
This document states that 'This information will be used by Microsoft to contact you if the Microsoft Security Response Center (MSRC) discovers that your customer data has been accessed by an unlawful or unauthorized party.'

I was wondering if it was also possible to set up a mailbox where alerts & recommendations gathered by Azure security center can be collected, therefore partly eliminating the need to constantly review the security center dashboard

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0a455a24-920e-f9f8-7a6f-60b5f4019acd
* Version Independent ID: e6a4d8e2-0ada-e535-810f-5eb19e45ee1e
* Content: [Geef de contactgegevens voor beveiliging in Azure Security Center](https://docs.microsoft.com/nl-nl/azure/security-center/security-center-provide-security-contact-details)
* Content Source: [articles/security-center/security-center-provide-security-contact-details.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/security-center/security-center-provide-security-contact-details.md)
* Service: **security-center**
* GitHub Login: @TerryLanfear
* Microsoft Alias: **terrylan**

**Comment by LisandroSu** [comment]
Hello, @sebastiaanvroom 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
