### ISSUE TITLE
HTTP POST to run the example

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-docs.nl-nl#96]
You are stating that we need to submit an HTTP POST to run the sample. What is your suggested way of submitting this HTTP POST?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 3b6ce511-60d0-9d1a-cf6f-c955adeae20b
* Version Independent ID: 0da09c8f-0a2f-26e4-2948-fcb43f67e251
* Content: [Werken in duurzame functies - Azure-koppeling](https://docs.microsoft.com/nl-nl/azure/azure-functions/durable-functions-sequence)
* Content Source: [articles/azure-functions/durable-functions-sequence.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-functions/durable-functions-sequence.md)
* Service: **azure-functions**
* GitHub Login: @cgillum
* Microsoft Alias: **azfuncdf**

**Comment by LisandroSu** [comment]
Hello, @cveld 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by cveld** [comment]
Hi Lisandro,

I don't fully understand your response. My question is related to the
statement in the documentation that the reader should execute an http post
request but no further clues are giving how this should be done.
It would be great if you could add at least one suggestion to the text
which tooling to use.

Regards,
Carl

Op ma 29 okt. 2018 20:45 schreef Lisandro <notifications@github.com>:
