### ISSUE TITLE
Clarify/Update the ADFS pfx part

### ISSUE THREAD

**Issue by JurreHeesbeen** [MicrosoftDocs/azure-docs.nl-nl#97]
I think the following parts of the instruction could do with some clarification:
	- Make sure that you have access to the certificate .pfx file with the private key that was issued by ADFS.
	- You need to store your ADFS certificate in your Azure AD B2C tenant

The way I read this is that it implies I must ask our customers ADFS admin to send us their private key pfx and store (and maintain) one for every ADFS federation we configure (a lot). This would be very labor intensive (they will need to be renewed), not to mention our customer's security officers getting the creeps over us asking for their private keys.

So I've configured the following (as I would expect it to be and how it was for instance with Microsoft ACS). I've created a single policy key containing a private key for all our SAML federations with customer ADFS and refer to that same key in all ADFS saml profiles. When a customer configures their federation on their ADFS server this certificate will be imported as the signature verification certificate and everything works as it should. Since it is our certificate, renewal is managed by us (and only for one certificate).

Can you confirm that this is a correct way to configure B2C ADFS Saml federations and if that's the case update the manual?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: e14a5d4c-5125-8ed2-7fda-38aee1296b76
* Version Independent ID: 054d298b-937e-9f01-ae56-7025e47e4eec
* Content: [AD FS toevoegen als een SAML-id-provider met behulp van aangepaste beleidsregels in Azure Active Directory B2C](https://docs.microsoft.com/nl-nl/azure/active-directory-b2c/active-directory-b2c-custom-setup-adfs2016-idp)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-custom-setup-adfs2016-idp.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/active-directory-b2c/active-directory-b2c-custom-setup-adfs2016-idp.md)
* Service: **active-directory**
* GitHub Login: @davidmu1
* Microsoft Alias: **davidmu**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #17918](https://github.com/MicrosoftDocs/azure-docs/issues/17918) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @JurreHeesbeen,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/17918.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
